from requests_html import HTMLSession

session = HTMLSession()
resp = session.get(f'https://habr.com/ru/company/yandex/blog/508180/')

title = str(resp.html.xpath('//title/text()'))
h1 = str(resp.html.xpath('//span[@class="post__title-text"]/text()'))
keywords = str(resp.html.xpath('//meta[@name="keywords"]/@content'))
description = str(resp.html.xpath('//meta[@name="description"]/@content')).replace('\\r\\n','')
post = str(resp.html.xpath('//div[@id = "post-content-body"]/text()'))
post = str(post).replace(r"'\n',","")
post = str(post).replace(r"'\r\n","")
post = str(post).replace(r"',","")
post = str(post).replace(r"'.","")
post = str(post).replace(r"'","")
post = str(post).replace(r"  ","")
print(title)
print(h1)
print(keywords)
print(description)
print(post)
